### ISSUE TITLE
GeoJSON Kabupaten Cilacap

### ISSUE THREAD

**Issue by kulokenci** [Bhulbul/satu-api#1]
Untuk GeoJSON Kab Cilacap tidak bisa saya gunakan, berikut saya lampirkan file GeoJSON yang berhasil saya gunakan.
[KAB_CILACAP.json.txt](https://github.com/Bhulbul/satu-api/files/10206515/KAB_CILACAP.json.txt)

**Comment by kulokenci** [comment]
![image](https://user-images.githubusercontent.com/17036835/207009998-de5061bf-676b-46fe-b354-a3c64ecae425.png)

**Comment by Bhulbul** [comment]
Terima kasih untuk informasi dan kontribusinya. Ijin saya masukkan geojson-nya ke data utama
