### ISSUE TITLE
[GeoJSON] Kota Tangerang Selatan

### ISSUE THREAD

**Issue by bgustyp** [Bhulbul/satu-api#2]
Belum tersedianya GeoJson untuk wilayah kota tangerang selatan. berikut saya sertakan GeoJSON untuk wilayah tersebut.

[KOTA_TANGERANG_SELATAN.json.txt](https://github.com/Bhulbul/satu-api/files/12509143/KOTA_TANGERANG_SELATAN.json.txt)

**Comment by Bhulbul** [comment]
Oke, Terima kasih banyak
